services:
  app:
    build:
      context: .
      args:
        APP_API_KEY: ${APP_API_KEY}
        PAGE_SIZE: ${PAGE_SIZE}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 8080
      SERVICE_FQDN_APP_8080: /
    expose:
      - "8080"
