services:
  app:
    build:
      context: .
      args:
        API_TOKEN: ${API_TOKEN}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 8080
      SERVICE_FQDN_APP_8080: /
    expose:
      - "8080"
